// Breaking News
$(document).ready(function(){var e="https://TestLiive.blogspot.com/",t=5;$.ajax({url:"/feeds/posts/default?alt=json-in-script&amp;max-results="+t,type:"get",dataType:"jsonp",success:function(e){function t(){$("#d-tubebreaking li:first").slideUp(function(){$(this).appendTo($("#d-tubebreaking ul")).slideDown()})}var n,r,a="",i=e.feed.entry;if(void 0!==i){a="<ul>";for(var l=0;l<i.length;l++){for(var s=0;s<i[l].link.length;s++)if("alternate"==i[l].link[s].rel){n=i[l].link[s].href;break}r=i[l].title.$t,a+='<li><i class="fa fa-check-square"></i><a href="'+n+'" target="_blank">'+r+"</a></li>"}a+="</ul>",$("#d-tubebreaking").html(a),setInterval(function(){t()},5e3)}else $("#d-tubebreaking").html("<span>There nothing here?</span>")},error:function(){$("#d-tubebreaking").html("<strong>Error Loading Feed!</strong>")}})});
//LazyJS & lazyCSS 
function lazyJS(e){var t=!1;window.addEventListener("scroll",function(){(0!=document.documentElement.scrollTop&&!1===t||0!=document.body.scrollTop&&!1===t)&&(function(){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src=e;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n)}(),t=!0)},!0)}
function lazyCSS(e){var t=!1;window.addEventListener("scroll",function(){(0!=document.documentElement.scrollTop&&!1===t||0!=document.body.scrollTop&&!1===t)&&(function(){var t=document.createElement("link");t.type="text/css",t.rel="stylesheet",t.href=e;var n=document.getElementsByTagName("link")[0];n.parentNode.insertBefore(t,n)}(),t=!0)},!0)}
//Full screen
function srClk(){var s=document.getElementById("header-area");if(s.classList)s.classList.toggle("src-active");else{var e=s.className.split(" "),a=e.indexOf("src-active");a>=0?e.splice(a,1):e.push("src-active"),s.className=e.join(" ")}}function expandMore(){var s=document.getElementById("plus-share");if(s.classList)s.classList.toggle("expand");else{var e=s.className.split(" "),a=e.indexOf("expand");a>=0?e.splice(a,1):e.push("expand"),s.className=e.join(" ")}}function singelCol(){var s=document.getElementById("outer-wrapper");if(s.classList)s.classList.toggle("singel");else{var e=s.className.split(" "),a=e.indexOf("singel");a>=0?e.splice(a,1):e.push("singel"),s.className=e.join(" ")}}
// Floating Menu
$(function(){var e=$(document).scrollTop();var t=$(".float_wrapper").outerHeight();$(window).scroll(function(){var n=$(document).scrollTop();if($(document).scrollTop()>=50){$(".float_wrapper").css("position","fixed")}else{$(".float_wrapper").css("position","fixed")}if(n>t){$(".float_wrapper").addClass("scroll")}else{$(".float_wrapper").removeClass("scroll")}if(n>e){$(".float_wrapper").removeClass("no-scroll")}else{$(".float_wrapper").addClass("no-scroll")}e=$(document).scrollTop()})})
//Navigation_bar
$(document).ready(function(){$(".M-Toggle").click(function(){$(".NavBar, .HideNavigation").toggleClass("show-menu")}),$(".HideNavigation").click(function(){$(".NavBar,.HideNavigation").removeClass("show-menu")});function e(e,n){this.el=e||{},this.multiple=n||!1,this.el.find(".nav-submenu").on("click",{el:this.el,multiple:this.multiple},this.dropdown)}e.prototype.dropdown=function(e){var n=e.data.el;$this=$(this),$next=$this.next(),$next.slideToggle(),$this.parent().toggleClass("show-menu"),e.data.multiple||n.find(".nav-sub").not($next).slideUp().parent().removeClass("show-menu")};new e($(".M-Toggle"),!1)});
//Labels Style
$(function(){$(".Label h2").on("click",function(n){$(this).toggleClass("on").next().slideToggle(200),n.stopPropagation()}),$(document.body).on("click",function(){$(".Label").find(".on").removeClass("on").next().slideUp(200)})});
// SharingModal Closeing
$(".showSharing").click(function(){$(".sharingModal").addClass("active")}),$(".close").click(function(){$(".sharingModal").removeClass("active")}),$(".Closeing").click(function(){$(".sharingModal").removeClass("active")});
// Lightbox image
const URLimg=document.querySelector("#URLimg");let enlargeMessages=document.querySelectorAll(".IMGcoating svg ");const IMGviewer=document.getElementById("IMGviewer"),overlay=document.querySelectorAll(".IMGcoating"),IMGviewerContainer=document.querySelector(".imgContainer");for(let e=0;e<enlargeMessages.length;e++)enlargeMessages[e].addEventListener("click",imgClick);function imgClick(e){IMGviewer.style.display="block",URLimg.src=e.target.parentNode.previousElementSibling.src}function clickOutside(e){e.target!=IMGviewer&&e.target!=IMGviewerContainer||(IMGviewer.style.display="none")}window.addEventListener("click",clickOutside),$(".HideIMG").click(function(){$(".IMGviewer").each(function(){this.style.display="none"})});
//Ripple_Effect_button          
!function(e){e(".d-t-ripple").click(function(c){var a=e(this);0===a.find(".dT-ripple").length&&a.append("<span class='dT-ripple'></span>");var b=a.find(".dT-ripple");if(b.removeClass("animate"),!b.height()&&!b.width()){var d=Math.max(a.outerWidth(),a.outerHeight());b.css({height:d,width:d})}
d=c.pageX-a.offset().left-b.width()/2;c=c.pageY-a.offset().top-b.height()/2;b.css({top:c+"px",left:d+"px"}).addClass("animate")})}(jQuery);
// Search  
let SEARCH=document.getElementById('H-search');let BACK_SEARCH=document.getElementById('back');let OVERLAY=document.getElementById('overlay_search');SEARCH.addEventListener('focus',()=>{document.getElementById('header').classList.add('show');OVERLAY.classList.add('show');});BACK_SEARCH.addEventListener('click',()=>{document.getElementById('header').classList.remove('show');OVERLAY.classList.remove('show');});
/* Dropdown Navigation Bar */ 
const linkCollapse=document.getElementsByClassName("RotaIcon");for(var i=0;i<linkCollapse.length;i++)linkCollapse[i].addEventListener("click",function(){const l=this.nextElementSibling;l.classList.toggle("showDropMenu");const e=l.previousElementSibling;e.classList.toggle("rotatePlus")});
//copyURL
function copyFunction(){document.getElementById("getlink").select(),document.execCommand("copy"),document.getElementById("sharingNotif").innerHTML="<span>Link copied!</span>" }; var uri = window.location.toString();if (uri.indexOf("?m=1","?m=1") > 0) {var clean_uri = uri.substring(0, uri.indexOf("?m=1"));window.history.replaceState({}, document.title, clean_uri);}
// // Bottom Sheet important
const bottomSheet=document.querySelector(".bottom-sheet-container");const button=document.querySelector(".button");const closeButton=document.querySelector(".close-button");function toggleBottomSheet(){bottomSheet.classList.toggle("show-bottom-sheet")};bottomSheet.addEventListener('click',function(e){if(e.target===bottomSheet){toggleBottomSheet()}})
button.addEventListener('click',function(e){toggleBottomSheet()});closeButton.addEventListener('click',function(e){toggleBottomSheet()})
// Ripple Header 
document.body.addEventListener("mousedown",(function(t){for(var e=t.target;e&&(!e.classList||!e.classList.contains("ripple"));)e=e.parentNode;if(e&&e.classList.contains("ripple")){var o=e.getBoundingClientRect(),i=o.left,s=o.top,d=e.offsetWidth,l=e.offsetHeight,a=(e.offsetTop,e.offsetLeft,t.clientX-i),n=t.clientY-s,r=Math.max(a,d-a),p=Math.max(n,l-n),c=window.getComputedStyle(e),f=Math.sqrt(r*r+p*p),m=document.createElement("div"),u=document.createElement("div");e.classList.contains("ripple-light")?m.classList.add("ripple-light"):e.classList.contains("Ripple_2")&&m.classList.add("Ripple_2"),m.classList.add("ripple-effect"),u.classList.add("ripple-container"),u.appendChild(m),document.body.appendChild(u),m.style.marginLeft=a+"px",m.style.marginTop=n+"px",u.style.left=i+((window.pageXOffset||document.scrollLeft)-(document.clientLeft||0)||0)+"px",u.style.top=s+((window.pageYOffset||document.scrollTop)-(document.clientTop||0)||0)+"px",u.style.width=d+"px",u.style.height=l+"px",u.style.borderTopLeftRadius=c.borderTopLeftRadius,u.style.borderTopRightRadius=c.borderTopRightRadius,u.style.borderBottomLeftRadius=c.borderBottomLeftRadius,u.style.borderBottomRightRadius=c.borderBottomRightRadius,setTimeout((function(){m.style.width=2*f+"px",m.style.height=2*f+"px",m.style.marginLeft=a-f+"px",m.style.marginTop=n-f+"px"}),0),setTimeout((function(){m.style.backgroundColor="rgba(0, 0, 0, 0)"}),250),setTimeout((function(){m.remove(),u.remove()}),650)}}));
// SHOW NavBar
const showMenu=(e,n)=>{const o=document.getElementById(e),t=document.getElementById(NavBarId);e&&NavBarId&&o.addEventListener("click",()=>{t.classList.toggle("show-menu"),o.classList.toggle("bx-x")})};showMenu("he-toggle","NavBar");const linkColor=document.querySelectorAll(".NavBarLink");function colorLink(){linkColor.forEach(e=>e.classList.remove("active")),this.classList.add("active")}linkColor.forEach(e=>e.addEventListener("click",colorLink));

// Real-Time Post View Counter
const viewSeting={blogID:"4370828723609442607",databaseUrl:"https://myview-99ed2-default-rtdb.firebaseio.com",abbreviation:!0,lazyload:!0};function loadJs(e,t,a,s){let o=document.createElement("script");t&&(o.id=t),o.async=a,o.defer=a,o.src=e,s&&(o.onload=s),document.getElementsByTagName("head")[0].appendChild(o)}function abvr(e){var t=Math.sign(Number(e));return 1e9<=Math.abs(Number(e))?t*(Math.abs(Number(e))/1e9).toFixed(2)+"B":1e6<=Math.abs(Number(e))?t*(Math.abs(Number(e))/1e6).toFixed(2)+"M":1e3<=Math.abs(Number(e))?t*(Math.abs(Number(e))/1e3).toFixed(2)+"K":Math.abs(Number(e))}function loadPostVw(){for(var e=document.querySelectorAll(".DtVIEWS"),t=firebase.database(),a=0;a<e.length;a++){var s=e[a],o=s.getAttribute("data-id");(o=t.ref("BlogID_"+viewSeting.blogID+"/PostID_"+o)).once("value",function(t,a){return function(e){0<(e=e.exists()?e.val():0)&&(t.setAttribute("data-view",viewSeting.abbreviation?abvr(e):e),t.classList.remove("HideViews")),"true"==t.getAttribute("data-add")&&(t.setAttribute("data-add",!1),e=parseInt(e)+1,a.set(e))}}(s,o))}}function postVw(){loadJs("https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js","fb-app",!0,()=>{loadJs("https://www.gstatic.com/firebasejs/8.10.1/firebase-database.js","fb-db",!0,()=>{var e={};e.databaseURL=viewSeting.databaseUrl,firebase.initializeApp(e),loadPostVw()})})}if(!0===viewSeting.lazyload){var a=[],b=[];let t=()=>{0==a.length&&null==localStorage.getItem("DTviews")&&(localStorage.setItem("DTviews",1),postVw())};window.addEventListener("scroll",e=>{(0!=document.documentElement.scrollTop&&0==b.length||0!=document.body.scrollTop&&0==b.length)&&t()},!0),document.getElementsByTagName("body")[0].addEventListener("click",e=>{t()}),localStorage.getItem("DTviews")&&postVw()}else postVw();
// Greet users
var now=new Date,currentHour=now.getHours(),greetings=[{time:0,greet:"🌜 Sweet dreams, pup!",class:"night"},{time:6,greet:"🌞 Good doggy morning!",class:"morning"},{time:12,greet:"🦴 Woof, lunchtime!",class:"afternoon"},{time:18,greet:"🌅 Good evening, pup!",class:"evening"},{time:24,greet:"😴 Sleep tight, doggo!",class:"night"}],todayGreeting=greetings.find(function(e){return currentHour>=e.time&&currentHour<e.time+6}),message=document.getElementById("message");message.innerHTML=todayGreeting.greet,message.className=todayGreeting.class;
